# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3307056d9b98183f7039bbee94331e296d6f7f10d2b4bf0fbb10eea373abb3217deff4838c4bbe2d2eb61d6d6523e624b97af37b7c22e73a2677c2ecc1cfb00b

test:
  secret_key_base: ffd1e690154bf5db5c6c4f28d5e2d1dd9d5303e912897068077834f077f3414f1b75784ed2f6a699c1885e69dc9b53a8d37ba4571e9a7179d8cf8accda24e6ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
