# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abe5342600399f623e0be6dab4000938c3a0cfc55e6f3f7721727bc98abd50ae95d37a8e3d0b617970060e6d39cffdc0436648215c70984310a1a1c2d44192fc

test:
  secret_key_base: bacc4910a06dc4859e7f9a52ed2c334a25512b34df6518dfc4ba1f8fc75283f5aecd2500ce4978699cadbf50389802a079936ec6012794681db4467f906159e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
